CREATE TABLE urls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_url TEXT UNIQUE NOT NULL,
    complete_url TEXT NOT NULL,
    fallback_url TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);

CREATE TABLE clicks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    short_url TEXT NOT NULL,
    headers JSONB,
    clicked_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    source_ip TEXT,
    CONSTRAINT fk_short_url
        FOREIGN KEY(short_url) REFERENCES urls(short_url)
);
